use aquareadb;
DROP TABLE IF EXISTS Piscina;
DROP TABLE IF EXISTS Persona;
DROP TABLE IF EXISTS Utente;
DROP TABLE IF EXISTS Staff;
DROP TABLE IF EXISTS Corso;
DROP TABLE IF EXISTS Luogo;
DROP TABLE IF EXISTS Iscritti;